auth_user/auth_user/urls.py
from django.contrib import admin
from django.urls import path, include
from auth_user_app import views


urlpatterns = [
    path('', views.index, name='index'), # home
    path('admin/', admin.site.urls),
    path('auth_user_app/', include('auth_user_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
]

auth_user/auth_user_app/urls.py
from django.urls import path
from auth_user_app import views

# template urls
app_name = 'auth_user_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    # path('user_login/', views.user_login, name='user_login'),
    path('user_login/', views.user_login, name='user_login'),
    
]

auth_user/auth_user_app/models.py
# from django.db import models
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# model means standard data table
# ModelForm means form for user input

class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.CASCADE)  # create relation with User (from django.contrib.auth.models import User)
    # OneToOneField is used to create a one to one relationship between two models 
    # since User table in sql table by default django create it, so we dont need to create it again and we just use one to one field
    
    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True) # 'profile_pics' must match with the under media folder name
    
    def __str__(self):
        return self.user.username

auth_user/auth_user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from auth_user_app.models import UserProfileInfo


# model means standard data table
# ModelForm means form for user input

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        
        
class UserProfileInfoForm(forms.ModelForm):
    
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

auth_user/auth_user_app/views.py
from django.shortcuts import render
from auth_user_app.forms import UserForm, UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'auth_user_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index')) # redirect to index after logout

def register(request):
    
    # we assumed user not registered yet
    registered = False # tell if someone is registered or not
    
    # if request is POST then grab info from form
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            
            user = user_form.save() #  save USER form to db, (user_form from forms.py UserForm class)
            user.set_password(user.password) # hash password .set_password() then
            user.save()  # save hashed password to db
            
            # extra information
            profile = profile_form.save(commit=False) # commit=False : dont save to db yet
            profile.user = user 
            # link one to one relationship with user_form = UserForm(data=request.POST) which come from forms.py UserForm model = User
            # it kinda create one to one relationship between User from django database and UserProfileInfo as extra attributes
            
            # check if they provided PP
            if 'profile_pic' in request.FILES: # FILES is used for file upload
                profile.profile_pic = request.FILES['profile_pic'] # kinda like Dict : 'profile_pic'
            
            # save the model
            profile.save()
            
            # then register
            registered = True
        else:
            print(user_form.errors, profile_form.errors) # tuppples
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    
    return render(request, 'auth_user_app/registration.html', 
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}) # for registration.html for context




# login section

def user_login(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user: # pass the auth 
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index')) # response redirect to index after login
            else:
                return HttpResponse("Your account is disabled/ not active") # if user is not active
        else:
            print("someone tried to login and failed")
            print(f"Username{username} and password {password}")
            return HttpResponse("Invalid login details supplied.")
        
    else:
        return render(request, 'auth_user_app/login.html',{}) # pass empty dict if you want

auth_user/auth_user_app/templates/auth_user_app/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                <li><a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-item nav-link" href="{% url 'auth_user_app:register' %}">Register</a></li>
                <!-- if user is authenticated(refer to views.py for def login user = authenticate()) -->
                {% if user.is_authenticated %}
                <li><a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="nav-item nav-link" href="{% url 'auth_user_app:user_login' %}">Login woi</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>


</body>

</html>

auth_user/auth_user_app/templates/auth_user_app/index.html
{% extends "auth_user_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>HOME Django Level Five</h1>
</div>

{% endblock %}

auth_user/auth_user_app/templates/auth_user_app/login.html
{% extends "auth_user_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <!-- using form action instead of using standard form tag-->
    <form action="{% url 'auth_user_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" id="username">
        <br>
        <label for="password">Password:</label>
        <input type="password" name="password" id="password">
        <br>
        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

auth_user/auth_user_app/templates/auth_user_app/registration.html
{% extends "auth_user_app/base.html" %}
{% load static %}
<!-- load image -->

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Just fill out the form.</h3>

    <!-- actual form-->
    <!-- enctype="multipart/form-data" is for image upload -->
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>

    {% endif %}

</div>

{% endblock %}